"""Add ML models for anomalies, patterns, and trends

Revision ID: 99a6a5f129a4
Revises: 31a4ee0a054d
Create Date: 2026-01-30 09:54:15.827739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a6a5f129a4'
down_revision: Union[str, Sequence[str], None] = '31a4ee0a054d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('deviation', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_anomalies_detected_at'), 'ml_anomalies', ['detected_at'], unique=False)
    op.create_index(op.f('ix_ml_anomalies_id'), 'ml_anomalies', ['id'], unique=False)
    op.create_table('ml_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('pattern_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('cluster_label', sa.String(length=100), nullable=True),
    sa.Column('similar_dates', sa.JSON(), nullable=True),
    sa.Column('characteristics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_patterns_id'), 'ml_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_ml_patterns_pattern_date'), 'ml_patterns', ['pattern_date'], unique=False)
    op.create_table('ml_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('analysis_period_days', sa.Integer(), nullable=False),
    sa.Column('trend_direction', sa.String(length=20), nullable=False),
    sa.Column('slope', sa.Float(), nullable=False),
    sa.Column('intercept', sa.Float(), nullable=False),
    sa.Column('r_squared', sa.Float(), nullable=False),
    sa.Column('mean_value', sa.Float(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('std_dev', sa.Float(), nullable=False),
    sa.Column('predictions', sa.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_trends_analyzed_at'), 'ml_trends', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_ml_trends_id'), 'ml_trends', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_trends_id'), table_name='ml_trends')
    op.drop_index(op.f('ix_ml_trends_analyzed_at'), table_name='ml_trends')
    op.drop_table('ml_trends')
    op.drop_index(op.f('ix_ml_patterns_pattern_date'), table_name='ml_patterns')
    op.drop_index(op.f('ix_ml_patterns_id'), table_name='ml_patterns')
    op.drop_table('ml_patterns')
    op.drop_index(op.f('ix_ml_anomalies_id'), table_name='ml_anomalies')
    op.drop_index(op.f('ix_ml_anomalies_detected_at'), table_name='ml_anomalies')
    op.drop_table('ml_anomalies')
    # ### end Alembic commands ###
